config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
	member do
	  get "execute"
	end
  end

  root 'pages#home'

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/help'

  resources :datasets

end

app/views/layouts/_map_background.html.erb
<div id="map_background" style= "width: 100%; height: 100%;"></div>

app/views/layouts/_messages.html.erb
<section id="flash_messages">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong><%= key.capitalize %>!</strong> <%= value %>
        </div>
    <% end %>
</section>

app/views/layouts/_navigation.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
	  <div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		  <span class="icon-bar"></span>
		</button>
		<%= link_to root_path, class: "navbar-brand active" do %>
			<span class="glyphicon glyphicon-home" aria-hidden="true"></span>
			<b><i>rfmprediction</i></b>
		<% end %>
		</div>
		<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>  Tasks <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to tasks_path do %>
									<span>All Tasks</span>
								<% end %>
							</li>
							<li><a href="<%= new_task_path %>">New Task</a></li>
						</ul>
					</li>
					<li>
						<%= link_to new_dataset_path do %>
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
							New Dataset
						<% end %>
					</li>
				</ul>

				<!--<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "About", pages_about_path %></li>
				<li><%= link_to "Contact", pages_contact_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li class="dropdown-header">Nav header</li>
							<li><a href="#">Separated link</a></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>-->
		</div><!--/.nav-collapse -->
	</div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', pages_about_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rfmprediction" %>">
        <title><%= content_for?(:title) ? yield(:title) : "rfmprediction" %></title>
        <%= include_gon %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
        <![endif]-->

        <%=
        #stylesheet_link_tag "sandstone", :media => "all"
        %>

        <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    </head>
    <body>
        <header>
            <%= render 'layouts/navigation' %>
        </header>

        <!--<main role="main">
        </main>-->

        <div class="">
            <%= render 'layouts/messages' %>
            <%= yield %>
        </div>

        <%= debug(params) if Rails.env.development? %>

        <!-- Javascripts
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <%=
        #javascript_include_tag "sandstone"
        %>
        <%= yield(:page_javascript) if content_for?(:page_javascript) %>

    </body>
</html>